src/main/kotlin/com/wafflestudio/snuttev/config/SecretsManagerConfig.kt
src/main/kotlin/com/wafflestudio/snuttev/controller/EvaluationController.kt
src/main/kotlin/com/wafflestudio/snuttev/dao/model/BaseEntity.kt
src/main/kotlin/com/wafflestudio/snuttev/scheduler/lecture_crawler/SnuttLectureSyncJobScheduler.kt
src/main/kotlin/com/wafflestudio/snuttev/scheduler/lecture_crawler/SnuttLectureSyncJobService.kt
src/main/kotlin/com/wafflestudio/snuttev/service/EvaluationService.kt
src/main/resources/application.yml
src/test/resources/application.yml

- BaseEntity의 특정 필드들 open 으로 변경

Apply SecretsManager & Modify default patterns

---

.github/workflows/test.yml
src/main/kotlin/com/wafflestudio/snuttev/DataLoader.kt
src/main/kotlin/com/wafflestudio/snuttev/dao/model/EvaluationComment.kt
src/main/kotlin/com/wafflestudio/snuttev/dao/model/Lecture.kt
src/main/kotlin/com/wafflestudio/snuttev/dao/model/LectureEvaluation.kt
src/main/kotlin/com/wafflestudio/snuttev/dao/model/SemesterLecture.kt
src/main/kotlin/com/wafflestudio/snuttev/scheduler/lecture_crawler/SnuttLectureSyncJobService.kt
src/test/kotlin/com/wafflestudio/snuttev/LectureRepositoryTest.kt
src/test/resources/application.yml

Fix tests and focus on many-to-one

---

build.gradle.kts
src/main/kotlin/com/wafflestudio/snuttev/config/QueryFactoryConfig.kt
src/main/kotlin/com/wafflestudio/snuttev/config/RedisConfig.kt
src/main/kotlin/com/wafflestudio/snuttev/config/SwaggerConfig.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/common/dto/PaginationResponse.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/evaluation/controller/EvaluationController.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/evaluation/dto/EvaluationResponse.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/evaluation/service/EvaluationService.kt
src/main/resources/application.yml

related issues: https://draft-waffle.atlassian.net/browse/SNUTT-304

SpringDoc-OpenAPI (Swagger)

---

src/main/kotlin/com/wafflestudio/snuttev/domain/evaluation/controller/EvaluationController.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/evaluation/dto/EvaluationResponse.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/evaluation/model/LectureEvaluation.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/evaluation/repository/LectureEvaluationRepository.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/evaluation/service/EvaluationService.kt

related issues: https://draft-waffle.atlassian.net/browse/SNUTT-308

SNUTT-308 GET /ev-service/v1/lectures/{id}/evaluations/users/me

---

src/main/kotlin/com/wafflestudio/snuttev/domain/lecture/controller/LectureController.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/lecture/dto/LectureResponse.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/lecture/repository/LectureRepository.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/lecture/service/LectureService.kt

related issues: https://draft-waffle.atlassian.net/browse/SNUTT-317

SNUTT-317 GET /ev-service/v1/lectures/id?course_number=&instructor=

---

src/main/kotlin/com/wafflestudio/snuttev/DataLoader.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/tag/dto/TagResponse.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/tag/model/TagGroup.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/tag/service/TagService.kt

related issues: https://draft-waffle.atlassian.net/browse/SNUTT-353

SNUTT-353 TagGroup 의 color 전달하기

---

.github/workflows/deploy-dev.yml
.github/workflows/test.yml
Dockerfile
Dockerrun-dev.aws.json

develop push 시 [snutt-ev-server-dev](https://ap-northeast-2.console.aws.amazon.com/elasticbeanstalk/home?region=ap-northeast-2#/environment/dashboard?applicationName=snutt-ev-server&environmentId=e-ywmfpbfkws)로 배포
main push 시 [snutt-ev-server-production](https://ap-northeast-2.console.aws.amazon.com/elasticbeanstalk/home?region=ap-northeast-2#/environment/dashboard?applicationName=snutt-ev-server&environmentId=e-tvyyex9rxp)로 배포 및 Slack 알림
EB Configurations 에서 환경 변수(JAVA_OPTS)로 profile 등 JVM 옵션 넣게 변경

dev 환경에 대한 배포 자동화 및 환경 변수로 profile 등 JVM 옵션 받기

---

src/main/kotlin/com/wafflestudio/snuttev/domain/lecture/dto/LectureRequest.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/lecture/service/LectureService.kt

커스텀으로 추가한 snutt 강의를 대응하기위해 nullable가능하게 하고 검색 시 필터링 하는 것으로 변경했습니다.

Change instructor and coursenumber of snutt to nullable

---

src/main/kotlin/com/wafflestudio/snuttev/DataLoader.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/evaluation/dto/EvaluationResponse.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/lecture/model/SemesterLecture.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/lecture/repository/SemesterLectureRepository.kt
src/main/kotlin/com/wafflestudio/snuttev/domain/lecture/service/LectureService.kt
src/main/kotlin/com/wafflestudio/snuttev/scheduler/lecture_crawler/SnuttLectureSyncJobService.kt
src/test/kotlin/com/wafflestudio/snuttev/scheduler/SnuttLectureSyncJobSliceTest.kt

related issues: https://draft-waffle.atlassian.net/browse/SNUTT-362

SNUTT-362 강의평 SemesterLecture 에서 lecture_number 구분하지 않기

---

core/src/main/kotlin/com/wafflestudio/snuttev/core/common/dto/SearchQueryDto.kt
core/src/main/kotlin/com/wafflestudio/snuttev/core/domain/lecture/repository/LectureRepositoryImpl.kt
core/src/main/kotlin/com/wafflestudio/snuttev/core/domain/lecture/service/LectureService.kt

Fix the search api bug when setting multiple semester tags

---

core/build.gradle.kts
core/src/main/kotlin/com/wafflestudio/snuttev/core/config/SecretsManagerConfig.kt

update secretsmanager dependency

---

.github/workflows/deploy-dev.yml

[ecr-image-tag-updater](https://github.com/wafflestudio/ecr-image-tag-updater)를 이용해 wafflestudio-cluster 에 자동 배포
1. GitHub Actions (in each repo) build and push docker image to ECR
2. ECR push event triggers AWS Lambda function
3. This Lambda function updates the image tag of the corresponding manifest file in [waffle-world](https://github.com/wafflestudio/waffle-world)
4. ArgoCD detects the change in the manifest file and deploys the new image

modify dev github actions

---

.github/workflows/deploy-dev.yml

#60 에서 미처 고려하지 못한 부분 수정. batch image 는 일단 기존 ECR repo 에 그대로 push.

batch image handling

---

.github/workflows/test.yml
api/src/main/kotlin/com/wafflestudio/snuttev/controller/EvaluationController.kt
api/src/main/resources/application.yml
batch/src/main/resources/application.yml
build.gradle.kts
core/src/main/kotlin/com/wafflestudio/snuttev/core/domain/evaluation/repository/LectureEvaluationRepository.kt
core/src/main/kotlin/com/wafflestudio/snuttev/core/domain/evaluation/service/EvaluationService.kt
core/src/main/resources/application-core.yml
core/src/main/resources/db/V1__init.sql
core/src/main/resources/db/V2__snuev_migration.sql
core/src/test/kotlin/com/wafflestudio/snuttev/core/SnuttevCoreTestApplication.kt
core/src/test/kotlin/com/wafflestudio/snuttev/core/domain/evaluation/service/EvaluationServiceTest.kt
core/src/test/resources/application-test.yml

https://draft-waffle.atlassian.net/browse/SNUTT-486

my evaluations page api

---

api/src/main/resources/application.yml

로그 보기가 너무 어렵고 성능에 악영향 줄거 같아서 끔

show_sql false for dev, prod

---

api/src/main/kotlin/com/wafflestudio/snuttev/controller/LectureController.kt
core/src/main/kotlin/com/wafflestudio/snuttev/core/domain/evaluation/repository/LectureEvaluationRepository.kt
core/src/main/kotlin/com/wafflestudio/snuttev/core/domain/lecture/service/LectureService.kt
core/src/test/kotlin/com/wafflestudio/snuttev/core/domain/lecture/service/LectureServiceTest.kt

- `/v1/users/me/lectures/latest?filter=no-my-evaluations` 와 같이 filter가 들어오면 작성된 강의평의 경우 제외하고 보여줍니다. 
- 테스트는 내일...

최근 강의에서 이미 강의평을 쓴 강의는 제거

---

api/src/main/kotlin/com/wafflestudio/snuttev/controller/LectureController.kt

- request attribute -> request param 으로 수정해서 query param을 받아오도록 #71 를 수정

`v1/users/me/lectures/latest` 에서 `filter` Query Param을 받아오도록 수정

---

api/src/main/kotlin/com/wafflestudio/snuttev/common/HealthCheckController.kt

liveness probe, readiness probe 용
기존 패턴과 맞춤

health-check endpoint

---

batch/src/main/kotlin/com/wafflestudio/snuttev/sync/SnuttLectureSyncJobConfig.kt
core/src/main/kotlin/com/wafflestudio/snuttev/core/common/util/SemesterUtils.kt
core/src/main/kotlin/com/wafflestudio/snuttev/core/domain/lecture/service/LectureService.kt

https://wafflestudio.slack.com/archives/C0PAVPS5T/p1688559509856879
아직 2023 2학기 시작도 안 했는데 유저가 실수로 미래 강의평 쓰는 것 방지

Filter semesterlectures to exclude next semester

---

core/build.gradle.kts
core/src/main/kotlin/com/wafflestudio/snuttev/core/domain/mongo/MongoService.kt
core/src/test/kotlin/com/wafflestudio/snuttev/core/domain/evaluation/service/EvaluationServiceTest.kt

이거 제거하면 Test CI 돌아갈때 mongodb 요청 실패하는거 기다리느라 좀 오래 걸리는 문제가 있어서 그것도 test에서 mongoService mock하는 방식으로 고쳤어요

MongoService에서 coroutine 제거
